development:
  platform: sqlserver
  host: wd-server-5
  database: CoreFramework_v3
  username: corev3
  password: corev3

test:
  platform: sqlserver
  host: chernogrebela
  database: core_modules
  username: coreLite
  password: coreLite

production:
  platform: sqlite
  database: App_Data\production.sqlite