development:
  platform: sqlserver
  host: database_host
  database: database_name
  username: database_username
  password: database_password
  properties:
    hibernate.cache.use_second_level_cache: true
    hibernate.cache.provider_class: NHibernate.Caches.SysCache.SysCacheProvider, NHibernate.Caches.SysCache

test:
  platform: sqlserver
  host: database_host
  database: database_name
  username: database_username
  password: database_password
  properties:
    hibernate.cache.use_second_level_cache: true
    hibernate.cache.provider_class: NHibernate.Caches.SysCache.SysCacheProvider, NHibernate.Caches.SysCache

production:
  platform: sqlite
  database: App_Data\production.sqlite