development:
  platform: sqlserver
  host: chernogrebela
  database: core
  username: coreLite
  password: coreLite
  properties:
    hibernate.cache.use_second_level_cache: true
    hibernate.cache.provider_class: NHibernate.Caches.SysCache.SysCacheProvider, NHibernate.Caches.SysCache

test:
  platform: sqlserver
  host: chernogrebela
  database: core
  username: coreLite
  password: coreLite
  properties:
    hibernate.cache.use_second_level_cache: true
    hibernate.cache.provider_class: NHibernate.Caches.SysCache.SysCacheProvider, NHibernate.Caches.SysCache

production:
  platform: sqlite
  database: App_Data\production.sqlite