development:
  platform: sqlserver
  host: wd-server-5
  database: CoreFramework_v3
  username: corev3
  password: corev3
  properties:
    hibernate.cache.use_second_level_cache: true
    hibernate.cache.provider_class: NHibernate.Caches.SysCache.SysCacheProvider, NHibernate.Caches.SysCache

test:
  platform: sqlite
  database: App_Data\core.sqlite

production:
  platform: sqlite
  database: App_Data\production.sqlite