development:
  platform: sqlserver
  host: chernogrebela
  database: core_modules666
  username: coreLite
  password: coreLite

test:
  platform: sqlserver
  host: chernogrebela
  database: core_modules
  username: coreLite
  password: coreLite

production:
  platform: sqlite
  database: App_Data\production.sqlite