// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using Framework.Mvc.T4MVC;
using T4MVC;
namespace Core.Forms.Controllers {
    public partial class FormAnswersController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected FormAnswersController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult FormAnswersDynamicGridData() {
            return new T4MVC_JsonResult(Area, Name, ActionNames.FormAnswersDynamicGridData);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ShowAnswers() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ShowAnswers);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ShowAnswerDetails() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ShowAnswerDetails);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public FormAnswersController Actions { get { return FormsMVC.FormAnswers; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly String Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly String Name = "FormAnswers";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly String ShowAll = "ShowAll";
            public readonly String FormAnswersDynamicGridData = "FormAnswersDynamicGridData";
            public readonly String ShowAnswers = "ShowAnswers";
            public readonly String ShowAnswerDetails = "ShowAnswerDetails";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly String FormAnswerDetails = "~/Views/FormAnswers/FormAnswerDetails.aspx";
            public readonly String FormAnswers = "~/Views/FormAnswers/FormAnswers.aspx";
            public readonly String FormsAnswersList = "~/Views/FormAnswers/FormsAnswersList.aspx";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_FormAnswersController: Core.Forms.Controllers.FormAnswersController {
        public T4MVC_FormAnswersController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult ShowAll() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ShowAll);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult FormAnswersDynamicGridData(int page, int rows, string search, string sidx, string sord) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.FormAnswersDynamicGridData);
            callInfo.RouteValueDictionary.Add("page", page);
            callInfo.RouteValueDictionary.Add("rows", rows);
            callInfo.RouteValueDictionary.Add("search", search);
            callInfo.RouteValueDictionary.Add("sidx", sidx);
            callInfo.RouteValueDictionary.Add("sord", sord);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ShowAnswers(long formWidgetId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ShowAnswers);
            callInfo.RouteValueDictionary.Add("formWidgetId", formWidgetId);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult ShowAnswers(long formWidgetId, int page, int rows, string sidx, string sord) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.ShowAnswers);
            callInfo.RouteValueDictionary.Add("formWidgetId", formWidgetId);
            callInfo.RouteValueDictionary.Add("page", page);
            callInfo.RouteValueDictionary.Add("rows", rows);
            callInfo.RouteValueDictionary.Add("sidx", sidx);
            callInfo.RouteValueDictionary.Add("sord", sord);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ShowAnswerDetails(long answerId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ShowAnswerDetails);
            callInfo.RouteValueDictionary.Add("answerId", answerId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
