// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC {
    public class SharedController {

        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            static readonly _EditorTemplates s_EditorTemplates = new _EditorTemplates();
            public _EditorTemplates EditorTemplates { get { return s_EditorTemplates; } }
            public partial class _EditorTemplates{
                public readonly string Boolean = "~/Views/Shared/EditorTemplates/Boolean.aspx";
                public readonly string ColorPicker = "~/Views/Shared/EditorTemplates/ColorPicker.aspx";
                public readonly string DateTime = "~/Views/Shared/EditorTemplates/DateTime.aspx";
                public readonly string DropDownList = "~/Views/Shared/EditorTemplates/DropDownList.aspx";
                public readonly string FckEditorText = "~/Views/Shared/EditorTemplates/FckEditorText.aspx";
                public readonly string ImageUpload = "~/Views/Shared/EditorTemplates/ImageUpload.aspx";
                public readonly string List = "~/Views/Shared/EditorTemplates/List.aspx";
                public readonly string MultilineText = "~/Views/Shared/EditorTemplates/MultilineText.aspx";
                public readonly string Password = "~/Views/Shared/EditorTemplates/Password.aspx";
                public readonly string String = "~/Views/Shared/EditorTemplates/String.aspx";
            }
            static readonly _Layouts s_Layouts = new _Layouts();
            public _Layouts Layouts { get { return s_Layouts; } }
            public partial class _Layouts{
                public readonly string ChangeLayout = "~/Views/Shared/Layouts/ChangeLayout.ascx";
                public readonly string Layout = "~/Views/Shared/Layouts/Layout.ascx";
                public readonly string LayoutSettings = "~/Views/Shared/Layouts/LayoutSettings.ascx";
            }
            static readonly _Pages s_Pages = new _Pages();
            public _Pages Pages { get { return s_Pages; } }
            public partial class _Pages{
                public readonly string PageModeForm = "~/Views/Shared/Pages/PageModeForm.ascx";
                public readonly string PageModePanel = "~/Views/Shared/Pages/PageModePanel.ascx";
            }
            static readonly _Users s_Users = new _Users();
            public _Users Users { get { return s_Users; } }
            public partial class _Users{
                public readonly string UserPanel = "~/Views/Shared/Users/UserPanel.ascx";
            }
            static readonly _Widgets s_Widgets = new _Widgets();
            public _Widgets Widgets { get { return s_Widgets; } }
            public partial class _Widgets{
                public readonly string WidgetCommonSettings = "~/Views/Shared/Widgets/WidgetCommonSettings.ascx";
                public readonly string WidgetContentHolder = "~/Views/Shared/Widgets/WidgetContentHolder.ascx";
                public readonly string WidgetCSSForm = "~/Views/Shared/Widgets/WidgetCSSForm.ascx";
                public readonly string WidgetCSSSettings = "~/Views/Shared/Widgets/WidgetCSSSettings.ascx";
                public readonly string WidgetLookAndFeelForm = "~/Views/Shared/Widgets/WidgetLookAndFeelForm.ascx";
                public readonly string WidgetLookAndFeelSettings = "~/Views/Shared/Widgets/WidgetLookAndFeelSettings.ascx";
                public readonly string WidgetPermissions = "~/Views/Shared/Widgets/WidgetPermissions.ascx";
                public readonly string WidgetSettings = "~/Views/Shared/Widgets/WidgetSettings.ascx";
                public readonly string WidgetsList = "~/Views/Shared/Widgets/WidgetsList.ascx";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
