// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using Framework.Mvc.T4MVC;
using T4MVC;
namespace Core.Profiles.Controllers {
    public partial class ProfileElementController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ProfileElementController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Show() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Show);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult LoadData() {
            return new T4MVC_JsonResult(Area, Name, ActionNames.LoadData);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult UpdateProfileElementPosition() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.UpdateProfileElementPosition);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ProfileElementController Actions { get { return ProfilesMVC.ProfileElement; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly String  Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly String  Name = "ProfileElement";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly String  Show = "Show";
            public readonly String  LoadData = "LoadData";
            public readonly String  UpdateProfileElementPosition = "UpdateProfileElementPosition";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly String  EditFormElement = "~/Views/ProfileElement/EditFormElement.aspx";
            public readonly String  FormElementEditor = "~/Views/ProfileElement/FormElementEditor.ascx";
            public readonly String  FormElements = "~/Views/ProfileElement/FormElements.aspx";
            public readonly String  New = "~/Views/ProfileElement/New.aspx";
            public readonly String  Show = "~/Views/ProfileElement/Show.aspx";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ProfileElementController: Core.Profiles.Controllers.ProfileElementController {
        public T4MVC_ProfileElementController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Show(long profileTypeId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Show);
            callInfo.RouteValueDictionary.Add("profileTypeId", profileTypeId);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult LoadData(int profileTypeId, int page, int rows, string search, string sidx, string sord) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.LoadData);
            callInfo.RouteValueDictionary.Add("profileTypeId", profileTypeId);
            callInfo.RouteValueDictionary.Add("page", page);
            callInfo.RouteValueDictionary.Add("rows", rows);
            callInfo.RouteValueDictionary.Add("search", search);
            callInfo.RouteValueDictionary.Add("sidx", sidx);
            callInfo.RouteValueDictionary.Add("sord", sord);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult UpdateProfileElementPosition(long profileElementId, int orderNumber) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.UpdateProfileElementPosition);
            callInfo.RouteValueDictionary.Add("profileElementId", profileElementId);
            callInfo.RouteValueDictionary.Add("orderNumber", orderNumber);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
