// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using Framework.Mvc.T4MVC;
using T4MVC;
namespace Core.Profiles.Controllers {
    public partial class ProfileHeaderController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ProfileHeaderController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult New() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.New);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Edit() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ChangeLanguage() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ChangeLanguage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Save() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Save);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Remove() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Remove);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ProfileHeaderController Actions { get { return ProfilesMVC.ProfileHeader; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly String  Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly String  Name = "ProfileHeader";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly String  New = "New";
            public readonly String  Edit = "Edit";
            public readonly String  ChangeLanguage = "ChangeLanguage";
            public readonly String  Save = "Save";
            public readonly String  Remove = "Remove";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly String  Edit = "~/Views/ProfileHeader/Edit.aspx";
            public readonly String  HeaderDetails = "~/Views/ProfileHeader/HeaderDetails.ascx";
            public readonly String  New = "~/Views/ProfileHeader/New.aspx";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ProfileHeaderController: Core.Profiles.Controllers.ProfileHeaderController {
        public T4MVC_ProfileHeaderController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult New(long profileTypeId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.New);
            callInfo.RouteValueDictionary.Add("profileTypeId", profileTypeId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult New(long profileTypeId, Core.Profiles.Models.ProfileHeaderViewModel profileHeader) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.New);
            callInfo.RouteValueDictionary.Add("profileTypeId", profileTypeId);
            callInfo.RouteValueDictionary.Add("profileHeader", profileHeader);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(long profileTypeId, long profileHeaderId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
            callInfo.RouteValueDictionary.Add("profileTypeId", profileTypeId);
            callInfo.RouteValueDictionary.Add("profileHeaderId", profileHeaderId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ChangeLanguage(long profileHeaderId, string culture) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ChangeLanguage);
            callInfo.RouteValueDictionary.Add("profileHeaderId", profileHeaderId);
            callInfo.RouteValueDictionary.Add("culture", culture);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Save(long profileTypeId, Core.Profiles.Models.ProfileHeaderViewModel model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Save);
            callInfo.RouteValueDictionary.Add("profileTypeId", profileTypeId);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Remove(long profileTypeId, long profileHeaderId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Remove);
            callInfo.RouteValueDictionary.Add("profileTypeId", profileTypeId);
            callInfo.RouteValueDictionary.Add("profileHeaderId", profileHeaderId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
